---
- name: Launch app
  docker_container:
    name: "{{ app_container }}"
    image: "{{ app_image }}"
    state: started
    pull: true
    restart_policy: always
    networks:
      - name: "{{ app_network }}"
    env:
      DATABASE_HOST: "{{ db_container }}"
      DATABASE_PASSWORD: "{{ db_password }}"
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
